/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rocket.gltf 
Author: ThatBrianDude (https://sketchfab.com/ThatBrianDude)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-rocket-89e69040a4874e789bd8d07f8b94d29a
Title: Low Poly Rocket
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { animated } from "@react-spring/three";

export default function Model({ props, rota }) {
  const { nodes, materials } = useGLTF('/rocket_model/rocket.gltf')

  return (
    <group {...props} dispose={null}>
      <animated.group rotation={rota.rot}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.015} position={[0, 0, -0.8]}>
          <mesh geometry={nodes.Sphere_Textire_Atlas_0.geometry} material={materials.Textire_Atlas} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Torus001_Material001_0.geometry} material={materials['Material.001']} position={[0, 108.087, -68.829]} rotation={[0.209, 0, 0]} scale={[20.503, 20.272, 14.558]} />
        </group>
      </animated.group>
    </group>
  )
}

useGLTF.preload('/rocket_model/rocket.gltf')
