name: Build and Deploy Django + React App to Azure Web App - eptatelemetry

on:
  push:
    branches:
      - serveronly
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      ## BACKEND (DJANGO)
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Criar e ativar ambiente virtual
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Instalar dependências do Django
        run: |
          source venv/bin/activate
          pip install -r EPTALAUNCHSERVER/backend/requirements.txt

      - name: Aplicar migrações do Django
        run: |
          source venv/bin/activate
          cd EPTALAUNCHSERVER/backend
          python manage.py makemigrations
          python manage.py migrate
          python manage.py runserver